version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
       - export DOCKER_TAG=$(echo "v${CODEBUILD_SOURCE_VERSION}" | tr "/" "_")
       - make
